#!/bin/bash

echo "Make directories for domains"
mkdir -v /etc/nginx/sites-available
mkdir -v /etc/nginx/sites-enabled

echo "Install bash completions"
echo "" >> ~/.bashrc
echo 'alias ~~="cd /etc/nginx"' >> ~/.bashrc
echo ". ~/domain/.bash_completions" >> ~/.bashrc
echo "" >> .bashrc

ln -s /usr/local/bin/domain ~/domain/domain

#EOF#